# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e5jlqktPYnTo5YVhtdQhUUaK3LyQoBor
"""

n1 =  int(input('>>'))
n2 =  int(input('>>'))

soma  =  n1 +  n2
divisao  =  n1/n2
mult =  n1 * n2
sub =  n1 - n2

print('Soma ', soma)
print('Divisão ', divisao)
print('Multiplicação ', mult)
print('Subtração ', sub)